---
title: "Función Sapply para DF"
author: "Daniel Eduardo Macias Estrada"
date: "16/5/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Uso de la función sapply para data frames

```{r}
# Sapply- función para aplicar una función sobre las columnas del data frame

str(iris)
# Obtener el promedio de las primeras 4 columnas
sapply(subset(iris, select = 1:4), mean)
# Obtener la sumatoria de las primeras 4 columnas
sapply(iris[,1:4], sum)

# Función propia
f = function(x){sqrt(sum(x^2))}
sapply(iris[, 1:4], f)
```

### Parametro na.rm

```{r narm}
# na.rm - parametro para indicar que se ingore los posibles valores NA de las columnas

df = data.frame(C1 = c(1,2,NA,4), C2 = c(5,NA,6,3))
sapply(df, mean)
sapply(df, mean, na.rm = TRUE)
```


## Ejemplo de la función aggregate

```{r aggregate}
# aggregate - función que aplica una función sobre una columna del DF, 
# tomando en cuenta los niveles de los factores indicados
aggregate(cbind(Sepal.Length, Petal.Length) ~ Species, 
          data = iris, FUN = mean, na.rm = TRUE)
```

### Otro ejemplo

```{r aggregate2}
head(mtcars)
str(mtcars)
mtcars$cyl = as.factor(mtcars$cyl)
mtcars$gear = as.factor(mtcars$gear)
mtcars$carb = as.factor(mtcars$carb)
aggregate(mpg ~ cyl+gear+carb, 
          data = mtcars, 
          FUN = mean, 
          na.rm = TRUE)
```

## Attach o detach

`attach(d.f)` funciona haciendo que R entienda las variables del dataframe como variables globales, sin necesidad de acceder a las mismas con el simbolo de $

`detach(d.f)` le quita esta propiedad a las variables del dataframe


